version: '3'

services:
  gtc-frontend:
    image: go-to-cloud-docker.pkg.coding.net/release/go-to-cloud/gtc-frontend:1.0.0-rc7
    container_name: "gtc-frontend"
    depends_on:
      - gtc-service
    restart: always
    ports:
      - "8080:80"

  gtc-service:
    image: go-to-cloud-docker.pkg.coding.net/release/go-to-cloud/gtc:1.0.0-rc7
    container_name: "gtc-service"
    depends_on:
      - mysql
    restart: always
    environment:
      - ENV=dev
      - dbuser=root
      - dbpwd=123456
      - dburl=mysql
      - schema=gotocloud
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai"

  mysql:
    image: mysql:8.0
    container_name: "gtc-mysql"
    restart: always
    volumes:
        - "./mysql/data:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: gotocloud
        MYSQL_ROOT_PASSWORD: 123456
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
