// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/configure/artifact": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/artifact.Artifact"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/artifact.Artifact"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/artifact/bind": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/artifact.Artifact"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/artifact/image/{imageId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除镜像制品",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ImageID",
                        "name": "imageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/artifact/images/hashId/{hashId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除镜像制品",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "hashId",
                        "name": "hashId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "imagesId",
                        "name": "content",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/artifact/testing": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/artifact.Testing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/artifact/{id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ImageID.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/artifact.Artifact"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "制品仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ImageID.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/build/cmd": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "构建命令",
                "tags": [
                    "BuildConfigure"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"dot-net-3.1\"",
                        "description": "Build Env",
                        "name": "env",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/buildEnv.cmd"
                        }
                    }
                }
            }
        },
        "/api/configure/build/env": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "构建环境",
                "tags": [
                    "BuildConfigure"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/buildEnv.envGroup"
                            }
                        }
                    }
                }
            }
        },
        "/api/configure/builder/install/k8s": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "安装构建节点",
                "tags": [
                    "Builder"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/builder.OnK8sModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/builder/node": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "更新构建节点信息",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/builder.OnK8sModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/builder/node/{id}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "卸载构建节点",
                "tags": [
                    "Builder"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Node ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/builder/nodes/k8s": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "节点管理",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/builder.NodesOnK8s"
                            }
                        }
                    }
                }
            }
        },
        "/api/configure/builder/nodes/k8s/available": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看节点可用工作单元",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/builder.NodesOnK8s"
                            }
                        }
                    }
                }
            }
        },
        "/api/configure/coderepo": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scm.Scm"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scm.Scm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo/bind": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scm.Scm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo/testing": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scm.Testing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/coderepo/{id}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "代码仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CodeRepo.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/deploy/k8s": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "k8s环境配置",
                "tags": [
                    "Configure"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/k8s.K8s"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "k8s仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/k8s.K8s"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/deploy/k8s/bind": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "k8s仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/k8s.K8s"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/deploy/k8s/testing": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "k8s仓库配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/k8s.Testing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/configure/deploy/k8s/{id}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "k8s仓库配置",
                "tags": [
                    "Configure"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "K8sRepo.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Login Model",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/monitor/{k8s}/apps/delete": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除容器",
                "tags": [
                    "Monitor"
                ],
                "summary": "删除容器",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deploy.DeletePod"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/monitor/{k8s}/apps/delete/{deploymentId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除应用",
                "tags": [
                    "Monitor"
                ],
                "summary": "删除应用",
                "responses": {}
            }
        },
        "/api/monitor/{k8s}/apps/query/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "列出安装的应用",
                "tags": [
                    "Monitor"
                ],
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "force refresh",
                        "name": "force",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "project id",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "deployment id， 用于从部署方案中跳转到对应的应用",
                        "name": "deploymentId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "k8s repo id",
                        "name": "k8s",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deploy.DeploymentDescription"
                            }
                        }
                    }
                }
            }
        },
        "/api/monitor/{k8s}/apps/restart": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "重启容器",
                "tags": [
                    "Monitor"
                ],
                "summary": "重启容器",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deploy.RestartPods"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/monitor/{k8s}/apps/scale": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "伸缩容器",
                "tags": [
                    "Monitor"
                ],
                "summary": "伸缩容器",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deploy.ScalePods"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/monitor/{k8s}/pod/{deploymentId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "列出应用中的Pod信息",
                "tags": [
                    "Monitor"
                ],
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "force refresh",
                        "name": "force",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "deployment id， 用于从部署方案中跳转到对应的应用",
                        "name": "deploymentId",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "k8s repo id",
                        "name": "k8s",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/kube.PodDetailDescription"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "更新项目信息",
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.DataModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "创建新的项目",
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.DataModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/coderepo": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "列出当前账户已绑定的SCM平台及可见的代码仓库",
                "tags": [
                    "Projects"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.CodeRepoGroup"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看项目信息",
                "tags": [
                    "Projects"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.DataModel"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除项目仓库",
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/{projectId}/artifact": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "按项目获取仓库里的制品",
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/artifact.Artifact"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/artifact/{artifactId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取项目中的制品镜像",
                "tags": [
                    "Projects"
                ],
                "summary": "获取项目中的制品镜像",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Artifact Repo ID",
                        "name": "artifactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docker_image.Image"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/artifact/{artifactId}/tags": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取项目中的制品镜像",
                "tags": [
                    "Projects"
                ],
                "summary": "获取项目中的制品镜像",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/artifacts/{querystring}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取项目中的制品镜像",
                "tags": [
                    "Projects"
                ],
                "summary": "获取项目中的制品镜像",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/deploy/app": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "创建部署应用",
                "tags": [
                    "Projects"
                ],
                "summary": "创建部署应用",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deploy.Deployment"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/projects/{projectId}/deploy/app/{deploymentId}/history": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取部署方案",
                "tags": [
                    "Projects"
                ],
                "summary": "获取部署方案",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deploy.DeploymentHistory"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/deploy/apps": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取部署方案列表",
                "tags": [
                    "Projects"
                ],
                "summary": "获取部署方案列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deploy.Deployment"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/deploy/env": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取部署环境列表，目前仅支持K8s环境",
                "tags": [
                    "Projects"
                ],
                "summary": "获取部署环境列表，目前仅支持K8s环境",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/{projectId}/deploy/{id}": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "开始部署",
                "tags": [
                    "Projects"
                ],
                "summary": "开始部署",
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除部署应用",
                "tags": [
                    "Projects"
                ],
                "summary": "删除部署应用",
                "responses": {}
            }
        },
        "/api/projects/{projectId}/deploy/{id}/rollback/{historyId}": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "回滚部署",
                "tags": [
                    "Projects"
                ],
                "summary": "回滚部署",
                "responses": {}
            }
        },
        "/api/projects/{projectId}/deploy/{k8sRepoId}/namespaces": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "根据当前用户所属组织获取部署环境的可用名字空间",
                "tags": [
                    "Projects"
                ],
                "summary": "获取部署环境的可用名字空间",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/import": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "导入代码",
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.SourceCodeModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/{projectId}/imported": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看导入的代码",
                "tags": [
                    "Projects"
                ],
                "summary": "查看导入的代码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.SourceCodeImportedModel"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/pipeline": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取构建计划",
                "tags": [
                    "Projects"
                ],
                "summary": "获取构建计划",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pipeline.PlanModel"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "新建构建计划",
                "tags": [
                    "Projects"
                ],
                "summary": "新建构建计划",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pipeline.PlanModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/{projectId}/pipeline/state": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取构建计划状态",
                "tags": [
                    "Projects"
                ],
                "summary": "获取构建计划状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pipeline.PlanCardModel"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/pipeline/{id}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除构建计划",
                "tags": [
                    "Projects"
                ],
                "summary": "删除构建计划",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/{projectId}/pipeline/{id}/build": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "启动构建计划",
                "tags": [
                    "Projects"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/projects/{projectId}/pipeline/{pipelineId}/history": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "获取构建计划",
                "tags": [
                    "Projects"
                ],
                "summary": "获取构建计划",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pipeline.PlanModel"
                            }
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/sourcecode/{id}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除项目仓库",
                "tags": [
                    "Projects"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project.ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "SourceCode.ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/projects/{projectId}/src/{sourceCodeId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "列出仓库分支",
                "tags": [
                    "Projects"
                ],
                "summary": "列出仓库分支",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "新建或更新用户",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "新建或更新用户",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/auths": {
            "get": {
                "description": "获取当前用户拥有的权限点",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/info": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看用户信息",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/join/{orgId}": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "将成员加入/移除组织",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "OrgId",
                        "description": "OrgId",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/joined/{orgId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "列出加入指定组织的用户",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "OrgId",
                        "description": "OrgId",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/kinds": {
            "get": {
                "description": "所有Kind",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "列出所有用户",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/logout": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "注销登录",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/org": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "新建或更新组织",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "新建或更新组织",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/org/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "查看用户所属组织",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.Org"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/org/{orgId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除组织",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/{userId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "删除用户",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/{userId}/belongs": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "用户加入的组织",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/{userId}/join": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "将组织添加/移除用户（用户维度操作）",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/{userId}/password/reset": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "重置用户密码",
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "example": "string",
                        "description": "Request",
                        "name": "ContentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "artifact.Artifact": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isSecurity": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "orgLites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/artifact.OrgLite"
                    }
                },
                "orgs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "password": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "artifact.OrgLite": {
            "type": "object",
            "properties": {
                "orgId": {
                    "type": "integer"
                },
                "orgName": {
                    "type": "string"
                }
            }
        },
        "artifact.Testing": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isSecurity": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "buildEnv.cmd": {
            "type": "object",
            "properties": {
                "lintCheck": {
                    "type": "string"
                },
                "unitTest": {
                    "type": "string"
                }
            }
        },
        "buildEnv.envGroup": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "label": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "builder.NodesOnK8s": {
            "type": "object",
            "properties": {
                "agentVersion": {
                    "description": "代理版本",
                    "type": "string"
                },
                "availableWorkers": {
                    "description": "可用节点数",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "kubeConfig": {
                    "type": "string"
                },
                "maxWorkers": {
                    "description": "最大同时工作数量",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "orgLites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/builder.OrgLite"
                    }
                },
                "orgs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "workspace": {
                    "description": "工作空间（k8s名字空间）",
                    "type": "string"
                }
            }
        },
        "builder.OnK8sModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kubeConfig": {
                    "type": "string"
                },
                "maxWorkers": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "orgs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "workspace": {
                    "type": "string"
                }
            }
        },
        "builder.OrgLite": {
            "type": "object",
            "properties": {
                "orgId": {
                    "type": "integer"
                },
                "orgName": {
                    "type": "string"
                }
            }
        },
        "deploy.DeletePod": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "deployment id",
                    "type": "integer"
                },
                "podName": {
                    "type": "string"
                }
            }
        },
        "deploy.Deployment": {
            "type": "object",
            "properties": {
                "artifact": {
                    "type": "integer"
                },
                "artifactName": {
                    "type": "string"
                },
                "artifactTag": {
                    "type": "string"
                },
                "cpuLimits": {
                    "type": "string",
                    "example": "0"
                },
                "cpuRequest": {
                    "type": "string",
                    "example": "0"
                },
                "enableLimit": {
                    "type": "boolean"
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "text": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    }
                },
                "healthcheck": {
                    "type": "string"
                },
                "healthcheckPort": {
                    "type": "string",
                    "example": "0"
                },
                "id": {
                    "type": "integer"
                },
                "k8s": {
                    "type": "integer"
                },
                "k8sName": {
                    "type": "string"
                },
                "lastDeployAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "memLimits": {
                    "type": "string",
                    "example": "0"
                },
                "memRequest": {
                    "type": "string",
                    "example": "0"
                },
                "namespace": {
                    "type": "string"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "containerPort": {
                                "type": "string"
                            },
                            "nodePort": {
                                "type": "string"
                            },
                            "servicePort": {
                                "type": "string"
                            }
                        }
                    }
                },
                "replicate": {
                    "type": "integer"
                }
            }
        },
        "deploy.DeploymentCondition": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "deploy.DeploymentDescription": {
            "type": "object",
            "properties": {
                "availablePods": {
                    "description": "可用副本数",
                    "type": "integer"
                },
                "conditions": {
                    "description": "状态",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deploy.DeploymentCondition"
                    }
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "deployment.ID",
                    "type": "integer"
                },
                "name": {
                    "description": "应用名称",
                    "type": "string"
                },
                "namespace": {
                    "description": "名字空间",
                    "type": "string"
                },
                "replicas": {
                    "description": "副本数",
                    "type": "integer"
                },
                "unavailablePods": {
                    "description": "不可用副本数",
                    "type": "integer"
                }
            }
        },
        "deploy.DeploymentHistory": {
            "type": "object",
            "properties": {
                "artifact": {
                    "type": "integer"
                },
                "artifactName": {
                    "type": "string"
                },
                "artifactTag": {
                    "type": "string"
                },
                "cpuLimits": {
                    "type": "string",
                    "example": "0"
                },
                "cpuRequest": {
                    "type": "string",
                    "example": "0"
                },
                "deploymentId": {
                    "type": "integer"
                },
                "enableLimit": {
                    "type": "boolean"
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "text": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    }
                },
                "healthcheck": {
                    "type": "string"
                },
                "healthcheckPort": {
                    "type": "string",
                    "example": "0"
                },
                "id": {
                    "type": "integer"
                },
                "k8s": {
                    "type": "integer"
                },
                "k8sName": {
                    "type": "string"
                },
                "lastDeployAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "memLimits": {
                    "type": "string",
                    "example": "0"
                },
                "memRequest": {
                    "type": "string",
                    "example": "0"
                },
                "namespace": {
                    "type": "string"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "containerPort": {
                                "type": "string"
                            },
                            "nodePort": {
                                "type": "string"
                            },
                            "servicePort": {
                                "type": "string"
                            }
                        }
                    }
                },
                "replicate": {
                    "type": "integer"
                }
            }
        },
        "deploy.RestartPods": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "deployment id",
                    "type": "integer"
                }
            }
        },
        "deploy.ScalePods": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "deployment id",
                    "type": "integer"
                },
                "num": {
                    "type": "integer"
                }
            }
        },
        "docker_image.Image": {
            "type": "object",
            "properties": {
                "fullName": {
                    "description": "完整路径，包含项目名称，e.g. library/mysql:latest",
                    "type": "string"
                },
                "hashId": {
                    "type": "string"
                },
                "latestVersion": {
                    "type": "string"
                },
                "name": {
                    "description": "镜像名",
                    "type": "string"
                },
                "publishedAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "tags": {
                    "description": "Tag",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docker_image.Tag"
                    }
                }
            }
        },
        "docker_image.Tag": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "imageID": {
                    "type": "integer"
                },
                "isLatest": {
                    "type": "boolean"
                },
                "publishedAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                }
            }
        },
        "k8s.K8s": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kubeconfig": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orgLites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/k8s.OrgLite"
                    }
                },
                "orgs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "serverVersion": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "k8s.OrgLite": {
            "type": "object",
            "properties": {
                "orgId": {
                    "type": "integer"
                },
                "orgName": {
                    "type": "string"
                }
            }
        },
        "k8s.Testing": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kubeconfig": {
                    "type": "string"
                }
            }
        },
        "kube.ContainerDescription": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "kube.PodDetailDescription": {
            "type": "object",
            "properties": {
                "buildId": {
                    "description": "构建时使用的Pod，对应pipeline.last_run_id，即pipeline_history.id",
                    "type": "integer"
                },
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kube.ContainerDescription"
                    }
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qos": {
                    "type": "string"
                },
                "restartCounter": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.LoginModel": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "pipeline.PlanCardModel": {
            "type": "object",
            "properties": {
                "artifact_enabled": {
                    "type": "boolean"
                },
                "artifact_repo_id": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "buildEnv": {
                    "type": "string"
                },
                "deploy_enabled": {
                    "type": "boolean"
                },
                "dockerfile": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_name": {
                    "type": "string"
                },
                "lastBuildAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "lastBuildResult": {
                    "type": "integer"
                },
                "lint_check": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qa_enabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "source_code_id": {
                    "type": "integer"
                },
                "unit_test": {
                    "type": "string"
                },
                "workdir": {
                    "type": "string"
                }
            }
        },
        "pipeline.PlanModel": {
            "type": "object",
            "properties": {
                "artifact_enabled": {
                    "type": "boolean"
                },
                "artifact_repo_id": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "buildEnv": {
                    "type": "string"
                },
                "deploy_enabled": {
                    "type": "boolean"
                },
                "dockerfile": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_name": {
                    "type": "string"
                },
                "lint_check": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qa_enabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "source_code_id": {
                    "type": "integer"
                },
                "unit_test": {
                    "type": "string"
                },
                "workdir": {
                    "type": "string"
                }
            }
        },
        "project.CodeRepoGroup": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.GitSources"
                    }
                }
            }
        },
        "project.DataModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "org": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "project.GitSources": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "project.SourceCodeImportedModel": {
            "type": "object",
            "properties": {
                "codeRepoId": {
                    "description": "仓库ID",
                    "type": "integer"
                },
                "codeRepoOrigin": {
                    "type": "integer"
                },
                "createdBy": {
                    "description": "导入人",
                    "type": "string"
                },
                "id": {
                    "description": "代码ID",
                    "type": "integer"
                },
                "latestBuildAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "url": {
                    "description": "代码地址",
                    "type": "string"
                }
            }
        },
        "project.SourceCodeModel": {
            "type": "object",
            "properties": {
                "codeRepoId": {
                    "description": "仓库ID",
                    "type": "integer"
                },
                "url": {
                    "description": "代码地址",
                    "type": "string"
                }
            }
        },
        "response.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "cost": {
                    "type": "string"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "scm.OrgLite": {
            "type": "object",
            "properties": {
                "orgId": {
                    "type": "integer"
                },
                "orgName": {
                    "type": "string"
                }
            }
        },
        "scm.Scm": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "orgLites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scm.OrgLite"
                    }
                },
                "orgs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "origin": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "scm.Testing": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "origin": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "user.Org": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "integer"
                },
                "member_count": {
                    "type": "integer"
                },
                "name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
